name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 14
          platform: x64
      - name: Get Conan
        uses: turtlebrowser/get-conan@main
      - name: install dependencies
        run: |
          conan profile new default --detect
          conan profile update settings.compiler=clang default
          conan profile update settings.compiler.version=14 default
          sudo apt-get install -y libgtk2.0-dev
      - name: build dependencies
        run: cd etc && ./setup.Dependencies.sh
      - name: build
        run: ./setup.Release.sh
