name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get Conan
        uses: turtlebrowser/get-conan@main
      - name: Install and setup dependencies
        run: |
          sudo apt-get install -y clang-12 libc++-12-dev libc++abi-12-dev lld-12 libgtk2.0-dev

          conan profile new default --detect
          conan profile update settings.compiler=clang default
          conan profile update settings.compiler.version=12 default
          conan profile update settings.compiler.libcxx=libc++ default
      - name: Build
        run: |
          export CC=/usr/bin/clang-12
          export CPP=/usr/bin/clang-cpp-12
          export CXX=/usr/bin/clang++-12
          export LD=/usr/bin/ld.lld-12
          # export CMAKE_CXX_FLAGS=-stdlib=libc++ # Not working this way

          ./setup.Release.sh
      - name: Unit-Test
        working-directory: build/Release/bin
        run: |
          ./ticket-decoder-test
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ticket-decoder
          path: |
            build/Release/etc/*
            build/Release/lib/*
            build/Release/bin/ticket-decoder
